# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.imagesupload_images import ImagesuploadImages  # noqa: F401,E501
from swagger_server import util


class ImagesUploadBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, images: List[ImagesuploadImages]=None):  # noqa: E501
        """ImagesUploadBody - a model defined in Swagger

        :param images: The images of this ImagesUploadBody.  # noqa: E501
        :type images: List[ImagesuploadImages]
        """
        self.swagger_types = {
            'images': List[ImagesuploadImages]
        }

        self.attribute_map = {
            'images': 'images'
        }
        self._images = images

    @classmethod
    def from_dict(cls, dikt) -> 'ImagesUploadBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The images_upload_body of this ImagesUploadBody.  # noqa: E501
        :rtype: ImagesUploadBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def images(self) -> List[ImagesuploadImages]:
        """Gets the images of this ImagesUploadBody.


        :return: The images of this ImagesUploadBody.
        :rtype: List[ImagesuploadImages]
        """
        return self._images

    @images.setter
    def images(self, images: List[ImagesuploadImages]):
        """Sets the images of this ImagesUploadBody.


        :param images: The images of this ImagesUploadBody.
        :type images: List[ImagesuploadImages]
        """
        if images is None:
            raise ValueError("Invalid value for `images`, must not be `None`")  # noqa: E501

        self._images = images
