# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ImagesImageIdBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: bytearray=None, filename: str=None):  # noqa: E501
        """ImagesImageIdBody - a model defined in Swagger

        :param data: The data of this ImagesImageIdBody.  # noqa: E501
        :type data: bytearray
        :param filename: The filename of this ImagesImageIdBody.  # noqa: E501
        :type filename: str
        """
        self.swagger_types = {
            'data': bytearray,
            'filename': str
        }

        self.attribute_map = {
            'data': 'data',
            'filename': 'filename'
        }
        self._data = data
        self._filename = filename

    @classmethod
    def from_dict(cls, dikt) -> 'ImagesImageIdBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The images_image_id_body of this ImagesImageIdBody.  # noqa: E501
        :rtype: ImagesImageIdBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> bytearray:
        """Gets the data of this ImagesImageIdBody.


        :return: The data of this ImagesImageIdBody.
        :rtype: bytearray
        """
        return self._data

    @data.setter
    def data(self, data: bytearray):
        """Sets the data of this ImagesImageIdBody.


        :param data: The data of this ImagesImageIdBody.
        :type data: bytearray
        """

        self._data = data

    @property
    def filename(self) -> str:
        """Gets the filename of this ImagesImageIdBody.


        :return: The filename of this ImagesImageIdBody.
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename: str):
        """Sets the filename of this ImagesImageIdBody.


        :param filename: The filename of this ImagesImageIdBody.
        :type filename: str
        """

        self._filename = filename
