# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse201Zip(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, message: str=None, zip_id: str=None):  # noqa: E501
        """InlineResponse201Zip - a model defined in Swagger

        :param status: The status of this InlineResponse201Zip.  # noqa: E501
        :type status: str
        :param message: The message of this InlineResponse201Zip.  # noqa: E501
        :type message: str
        :param zip_id: The zip_id of this InlineResponse201Zip.  # noqa: E501
        :type zip_id: str
        """
        self.swagger_types = {
            'status': str,
            'message': str,
            'zip_id': str
        }

        self.attribute_map = {
            'status': 'status',
            'message': 'message',
            'zip_id': 'zip_id'
        }
        self._status = status
        self._message = message
        self._zip_id = zip_id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse201Zip':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201_zip of this InlineResponse201Zip.  # noqa: E501
        :rtype: InlineResponse201Zip
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this InlineResponse201Zip.


        :return: The status of this InlineResponse201Zip.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this InlineResponse201Zip.


        :param status: The status of this InlineResponse201Zip.
        :type status: str
        """

        self._status = status

    @property
    def message(self) -> str:
        """Gets the message of this InlineResponse201Zip.


        :return: The message of this InlineResponse201Zip.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InlineResponse201Zip.


        :param message: The message of this InlineResponse201Zip.
        :type message: str
        """

        self._message = message

    @property
    def zip_id(self) -> str:
        """Gets the zip_id of this InlineResponse201Zip.


        :return: The zip_id of this InlineResponse201Zip.
        :rtype: str
        """
        return self._zip_id

    @zip_id.setter
    def zip_id(self, zip_id: str):
        """Sets the zip_id of this InlineResponse201Zip.


        :param zip_id: The zip_id of this InlineResponse201Zip.
        :type zip_id: str
        """

        self._zip_id = zip_id
