# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ZipZipIdBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, file: str=None):  # noqa: E501
        """ZipZipIdBody - a model defined in Swagger

        :param file: The file of this ZipZipIdBody.  # noqa: E501
        :type file: str
        """
        self.swagger_types = {
            'file': str
        }

        self.attribute_map = {
            'file': 'file'
        }
        self._file = file

    @classmethod
    def from_dict(cls, dikt) -> 'ZipZipIdBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The zip_zip_id_body of this ZipZipIdBody.  # noqa: E501
        :rtype: ZipZipIdBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file(self) -> str:
        """Gets the file of this ZipZipIdBody.


        :return: The file of this ZipZipIdBody.
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file: str):
        """Sets the file of this ZipZipIdBody.


        :param file: The file of this ZipZipIdBody.
        :type file: str
        """

        self._file = file
